openapi: 3.0.0
info:
  title: Investitionsverwaltung API
  description: API zur Verwaltung von Investitionen
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Lokalerserver
 
paths:
  /massnahmen:
    get:
      tags:
        - Maßnahmen 
      summary: Liste aller Maßnahmen abrufen
      operationId: getMaßnahmen
      responses:
        '200':
          description: Liste von Maßnahmen erfolgreich abgerufen
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Massnahmen'
        '400':
          description: Ungültige Anfrage
        '500':
          description: Serverfehler
    post:
      tags:
        - Maßnahmen
      summary: Neue Maßnahme erstellen
      operationId: addMaßnahmen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Massnahmen'
      responses:
        '201':
          description: Maßnahme wurde erfolgreich erstellt
        '400':
          description: Ungültige Anfragedaten
        '500':
          description: Serverfehler
    put:
      tags:
        - Maßnahmen
      summary: Bestehende Maßnahme  aktualisieren
      operationId: updateMaßnahmen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Massnahmen'
      responses:
        '200':
          description: Maßnahme wurde erfolgreich aktualisiert
        '400':
          description: Ungültige Anfragedaten
        '404':
          description: Maßnahme wurde nicht gefunden
        '500':
          description: Serverfehler
  /massnahmen/{maßnahmeID}:
    get:
      tags:
        - Maßnahmen
      summary: Abrufen einer Maßnahme
      parameters:
        - in: path
          name: maßnahmeID
          schema:
            type: integer
          required: true
          description: ID der Maßnahme
      responses:
        '200':
          description: Die Maßnahme wurde erfolgreich übermittelt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Massnahmen'
        '404':
          description: Maßnahme wurde nicht gefunden
        '500':
          description: Serverfehler
    delete:
      tags:
        - Maßnahmen
      summary:  Maßnahme löschen
      parameters:
        - in: path
          name: maßnahmeID
          schema:
            type: integer
          required: true
          description: ID der Maßnahme
      responses:
        '200':
          description: Maßnahme erfolgreich gelöscht
        '404':
          description: Maßnahme wurde nicht gefunden
        '500':
          description: Serverfehler
        
  /investition:
    get:
      tags:
        - Investition
      summary: Liste aller Investitionen
      responses:
        '200':
          description: Erfolgreich alle Investitionen erhalten
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Investition'
    post:
      tags:
        - Investition
      summary: Neue Investitionen erstellen
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Investition'
      responses:
        '201':
          description: Investition erfolgreich erstellt
        '400':
          description: Ungültige Anfragedaten
        '500':
          description: Serverfehler
    put:
      tags:
        - Investition
      summary: Bestehende Investition aktualisieren
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Investition'
      responses:
        '200':
          description: Investition erfolgreich aktualisiert
        '400':
          description: Ungültige Anfragedaten
        '404':
          description: Investition wurde nicht gefunden
        '500':
          description: Serverfehler
  /investition/{investionsID}:
    get:
      tags:
        - Investition
      summary: Einzelne Investition abrufen
      parameters:
        - in: path
          name: investionsID
          schema:
            type: integer
          required: true
          description: ID der Investition
      responses:
        '200':
          description: Erfolgreich die Investition erhalten
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Massnahmen'
        '404':
          description: Investition wurde nicht gefunden
        '500':
          description: Serverfehler
    delete:
      tags:
        - Investition
      summary: Eine Investition löschen
      parameters:
        - in: path
          name: investionsID
          schema:
            type: integer
          required: true
          description: ID der Investition
      responses:
        '200':
          description: Investition erfolgreich gelöscht
        '404':
          description: Investition wurde nicht gefunden
        '500':
          description: Serverfehler
components:
  schemas:
    Massnahmen:
      type: object
      required:
        - maßnahmeID
        - dringlichkeit
        - inspektionselement
        - anmerkung
        - status
        - objektID
        - inspektionID
        - bauteil
      properties:
        maßnahmeID:
          type: integer
        dringlichkeit:
          type: string
          enum:
            - KURZFRISTIG
            - MITTELFRISTIG
            - LANGFRISTIG
        inspektionselement:
          type: string
        anmerkung:
          type: string
        status:
          type: string
          enum:
            - DURCHGEFÜHRT
            - OFFEN
            - NICHT_DURCHGEFÜHRT
        inspektionID:
          type: integer
        bauteil:
          type: string
    Investition:
      type: object
      required:
        - investionsID
        - maßnahmeID
        - jahr
        - kosten
        - anmerkung
      properties:
        investionsID:
          type: integer
        maßnahmeID:
          type: integer
        jahr:
          type: integer
        kosten:
          type: integer
        anmerkung:
          type: string
